#!/bin/sh
#
GIT_SHA=$(git rev-parse HEAD)
GIT_DIFF=$(git diff -s --exit-code || echo "-local")
GIT_COMMIT_HASH=$GIT_SHA$GIT_DIFF
BUILD_DATE=$(shell date --iso-8601=seconds)

cat <<"EOF" > ./lib/version/buildinfo.cpp
#############################################################################
### This file is generated by the Build/CI script                       #####
### .github/workflows/buildinfo.py for local development environment    #####
### .github/workflows/testbuildrelease.yml for CI environment           #####
### Changes will be overwritten on the next build                       #####
#############################################################################

#include "buildinfo.h"

const buildEnvironment buildInfo::theBuildEnvironment{buildEnvironment::local};
const buildType buildInfo::theBuildType{buildType::development};
const int buildInfo::mainVersionDigit   = 0;
const int buildInfo::minorVersionDigit  = 0;
const int buildInfo::patchVersionDigit  = 0;
const char* buildInfo::lastCommitTag    = "$GIT_COMMIT_HASH";
const char* buildInfo::buildTimeStamp   = "$BUILD_DATE";
EOF
